Repository IP2B2/Back-End, pull requests merged in 2025-05, with the labels that each got.

#18 103 implementare crud pentru lab document
  src/main/java/com/UAIC/ISMA/controller/EquipmentController.java
  src/main/java/com/UAIC/ISMA/controller/LabDocumentController.java
  src/main/java/com/UAIC/ISMA/repository/LabDocumentRepository.java
  src/main/java/com/UAIC/ISMA/service/LabDocumentService.java
  uploads/1745592235572_Product Backlog.docx
Labels: queued

#13 register refacut cu trimis mail functional
  src/main/java/com/UAIC/ISMA/controller/RegisterController.java
  src/main/resources/application.properties
Labels: ready-to-run

#20 #101 Am implementat serviciile si controllerul CRUD pentru AuditLog
  src/main/java/com/UAIC/ISMA/controller/AuditLogController.java
  src/main/java/com/UAIC/ISMA/mapper/AuditLogMapper.java
  src/main/java/com/UAIC/ISMA/service/AuditLogService.java
Labels: queued

#32 Notifications refactor and testing
  pom.xml
  src/main/java/com/UAIC/ISMA/IsmaApplication.java
  src/main/java/com/UAIC/ISMA/config/JwtUtil.java
  src/main/java/com/UAIC/ISMA/config/SecurityConfig.java
  src/main/java/com/UAIC/ISMA/config/UserDetailsImpl.java
  src/main/java/com/UAIC/ISMA/controller/NotificationController.java
  src/main/java/com/UAIC/ISMA/dao/Notification.java
  src/main/java/com/UAIC/ISMA/dto/NotificationDTO.java
  src/main/java/com/UAIC/ISMA/exception/ConflictException.java
  src/main/java/com/UAIC/ISMA/exception/GlobalExceptionHandler.java
  src/main/java/com/UAIC/ISMA/exception/NotificationNotFoundException.java
  src/main/java/com/UAIC/ISMA/exception/UnauthorizedException.java
  src/main/java/com/UAIC/ISMA/exception/UserNotFoundException.java
  src/main/java/com/UAIC/ISMA/mapper/NotificationMapper.java
  src/main/java/com/UAIC/ISMA/repository/NotificationRepository.java
  src/main/java/com/UAIC/ISMA/service/NotificationService.java
  src/main/resources/application.properties
  src/test/java/com/UAIC/ISMA/controller/NotificationControllerTest.java
  src/test/java/com/UAIC/ISMA/service/NotificationServiceTest.java
Labels: ready-to-run

#33 #128 code refactoring and unit tests for RequestApproval
  .github/workflows/pr-label-initial.yml
  src/main/java/com/UAIC/ISMA/controller/RequestApprovalController.java
  src/main/java/com/UAIC/ISMA/dto/RequestApprovalDTO.java
  src/main/java/com/UAIC/ISMA/exception/AccessRequestNotFoundException.java
  src/main/java/com/UAIC/ISMA/exception/RequestApprovalNotFoundException.java
  src/main/java/com/UAIC/ISMA/mapper/RequestApprovalMapper.java
  src/main/java/com/UAIC/ISMA/service/RequestApprovalService.java
  src/test/java/com/UAIC/ISMA/controller/RequestApprovalControllerTest.java
  src/test/java/com/UAIC/ISMA/service/RequestApprovalServiceTest.java
Labels: ready-to-run

#39 #129 refactorizare cod+teste unitare+modificari crud Equipment
  src/main/java/com/UAIC/ISMA/controller/EquipmentController.java
  src/main/java/com/UAIC/ISMA/dao/Equipment.java
  src/main/java/com/UAIC/ISMA/exception/EquipmentNotFoundException.java
  src/main/java/com/UAIC/ISMA/exception/LaboratoryNotFoundException.java
  src/main/java/com/UAIC/ISMA/mapper/EquipmentMapper.java
  src/main/java/com/UAIC/ISMA/service/EquipmentService.java
  src/test/java/com/UAIC/ISMA/controller/EquipmentControllerTest.java
  src/test/java/com/UAIC/ISMA/service/EquipmentServiceTest.java
Labels: ready-to-run

#42 #126 Refactorizare cod AuditLog + scriere teste unitare
  src/main/java/com/UAIC/ISMA/controller/AuditLogController.java
  src/main/java/com/UAIC/ISMA/exception/AuditLogNotFoundException.java
  src/main/java/com/UAIC/ISMA/mapper/AuditLogMapper.java
  src/main/java/com/UAIC/ISMA/service/AuditLogService.java
  src/test/java/com/UAIC/ISMA/controller/AuditLogControllerTest.java
  src/test/java/com/UAIC/ISMA/service/AuditLogServiceTest.java
Labels: ready-to-run

#37 #127 am refactorizat codul + teste unitare AccessRequest REFACUT!!!!
  .github/workflows/pr-label-initial.yml
  src/main/java/com/UAIC/ISMA/controller/AccessRequestController.java
  src/main/java/com/UAIC/ISMA/dao/AccessRequest.java
  src/main/java/com/UAIC/ISMA/service/AccessRequestService.java
  src/test/java/com/UAIC/ISMA/controller/AccessRequestControllerTest.java
  src/test/java/com/UAIC/ISMA/service/AccessRequestServiceTest.java
Labels: ready-to-run

#36 code-refactoring-and-unit-tests-for-LabDocument
  src/main/java/com/UAIC/ISMA/controller/LabDocumentController.java
  src/main/java/com/UAIC/ISMA/dao/LabDocument.java
  src/main/java/com/UAIC/ISMA/exception/LabDocumentNotFoundException.java
  src/main/java/com/UAIC/ISMA/mapper/LabDocumentsMapper.java
  src/main/java/com/UAIC/ISMA/service/LabDocumentService.java
  src/main/resources/application.properties
  src/test/java/com/UAIC/ISMA/controller/LabDocumentControllerTest.java
  src/test/java/com/UAIC/ISMA/service/LabDocumentServiceTest.java
Labels: ready-to-run

#35 #124 code refactoring and unit tests for VirtualAccess
  src/main/java/com/UAIC/ISMA/config/JwtFilter.java
  src/main/java/com/UAIC/ISMA/config/SecurityConfig.java
  src/main/java/com/UAIC/ISMA/controller/VirtualAccessController.java
  src/main/java/com/UAIC/ISMA/dao/VirtualAccess.java
  src/main/java/com/UAIC/ISMA/exception/VirtualAccessNotFoundException.java
  src/main/java/com/UAIC/ISMA/mapper/VirtualAccessMapper.java
  src/main/java/com/UAIC/ISMA/service/VirtualAccessService.java
  src/test/java/com/UAIC/ISMA/controller/VirtualAccessControllerTest.java
  src/test/java/com/UAIC/ISMA/service/VirtualAccessServiceTest.java
Labels: ready-to-run

#41 Ip25 #108 + #120 + #130
  src/main/java/com/UAIC/ISMA/controller/RequestDocumentController.java
  src/main/java/com/UAIC/ISMA/dao/RequestDocument.java
  src/main/java/com/UAIC/ISMA/dto/RequestDocumentDTO.java
  src/main/java/com/UAIC/ISMA/exception/RequestDocumentNotFoundException.java
  src/main/java/com/UAIC/ISMA/mapper/RequestDocumentMapper.java
  src/main/java/com/UAIC/ISMA/service/RequestDocumentService.java
  src/test/java/com/UAIC/ISMA/controller/RequestDocumentControllerTest.java
  src/test/java/com/UAIC/ISMA/service/RequestDocumentServiceTest.java
Labels: needs-work

#44 fixes
  src/main/java/com/UAIC/ISMA/controller/AuditLogController.java
  src/main/java/com/UAIC/ISMA/service/AuditLogService.java
  src/main/resources/application.properties
Labels: ready-to-run

#45 fixes
  src/test/java/com/UAIC/ISMA/controller/AuditLogControllerTest.java
  src/test/java/com/UAIC/ISMA/service/AuditLogServiceTest.java
Labels: ready-to-run

#43 CRUD pentru documentRequest - refacut
  .dockerignore
  .github/workflows/deploy-PR-backend.yml
  .github/workflows/deploy-backend.yml
  .github/workflows/label-merge-conflicts.yml
  .github/workflows/pr-label-initial.yml
  .github/workflows/pr-review-feedback.yml
  Dockerfile
  src/main/java/com/UAIC/ISMA/config/JwtFilter.java
  src/main/java/com/UAIC/ISMA/config/SecurityConfig.java
  src/main/java/com/UAIC/ISMA/controller/AccessRequestController.java
  src/main/java/com/UAIC/ISMA/controller/AuditLogController.java
  src/main/java/com/UAIC/ISMA/controller/EquipmentController.java
  src/main/java/com/UAIC/ISMA/controller/LabDocumentController.java
  src/main/java/com/UAIC/ISMA/controller/LaboratoryController.java
  src/main/java/com/UAIC/ISMA/controller/VirtualAccessController.java
  src/main/java/com/UAIC/ISMA/dao/AccessRequest.java
  src/main/java/com/UAIC/ISMA/dao/Equipment.java
  src/main/java/com/UAIC/ISMA/dao/LabDocument.java
  src/main/java/com/UAIC/ISMA/dao/VirtualAccess.java
  src/main/java/com/UAIC/ISMA/exception/AuditLogNotFoundException.java
  src/main/java/com/UAIC/ISMA/exception/EquipmentNotFoundException.java
  src/main/java/com/UAIC/ISMA/exception/LabDocumentNotFoundException.java
  src/main/java/com/UAIC/ISMA/exception/LaboratoryNotFoundException.java
  src/main/java/com/UAIC/ISMA/exception/VirtualAccessNotFoundException.java
  src/main/java/com/UAIC/ISMA/mapper/AuditLogMapper.java
  src/main/java/com/UAIC/ISMA/mapper/EquipmentMapper.java
  src/main/java/com/UAIC/ISMA/mapper/LabDocumentsMapper.java
  src/main/java/com/UAIC/ISMA/mapper/LaboratoryMapper.java
  src/main/java/com/UAIC/ISMA/mapper/VirtualAccessMapper.java
  src/main/java/com/UAIC/ISMA/service/AccessRequestService.java
  src/main/java/com/UAIC/ISMA/service/AuditLogService.java
  src/main/java/com/UAIC/ISMA/service/EquipmentService.java
  src/main/java/com/UAIC/ISMA/service/LabDocumentService.java
  src/main/java/com/UAIC/ISMA/service/LaboratoryService.java
  src/main/java/com/UAIC/ISMA/service/VirtualAccessService.java
  src/test/java/com/UAIC/ISMA/controller/AccessRequestControllerTest.java
  src/test/java/com/UAIC/ISMA/controller/AuditLogControllerTest.java
  src/test/java/com/UAIC/ISMA/controller/EquipmentControllerTest.java
  src/test/java/com/UAIC/ISMA/controller/LabDocumentControllerTest.java
  src/test/java/com/UAIC/ISMA/controller/LaboratoryControllerTest.java
  src/test/java/com/UAIC/ISMA/controller/VirtualAccessControllerTest.java
  src/test/java/com/UAIC/ISMA/service/AccessRequestServiceTest.java
  src/test/java/com/UAIC/ISMA/service/AuditLogServiceTest.java
  src/test/java/com/UAIC/ISMA/service/EquipmentServiceTest.java
  src/test/java/com/UAIC/ISMA/service/LabDocumentServiceTest.java
  src/test/java/com/UAIC/ISMA/service/LaboratoryServiceTest.java
  src/test/java/com/UAIC/ISMA/service/VirtualAccessServiceTest.java
Labels: ready-to-run

#52 BE-Opt-307- REFACUT
  src/main/java/com/UAIC/ISMA/controller/AccessRequestController.java
  src/main/java/com/UAIC/ISMA/dto/AccessRequestFilterDTO.java
  src/main/java/com/UAIC/ISMA/repository/AccessRequestRepository.java
  src/main/java/com/UAIC/ISMA/service/AccessRequestService.java
  src/test/java/com/UAIC/ISMA/controller/AccessRequestControllerFilterTest.java
  src/test/java/com/UAIC/ISMA/service/AccessRequestServiceFilterTest.java
Labels: ready-to-run

#54 fixed bugs
  src/main/java/com/UAIC/ISMA/config/JwtUtil.java
  src/main/java/com/UAIC/ISMA/config/SecurityConfig.java
  src/main/java/com/UAIC/ISMA/controller/RegisterController.java
  src/main/java/com/UAIC/ISMA/dto/RegisterRequest.java
  src/main/java/com/UAIC/ISMA/dto/RegisterResponse.java
  src/main/java/com/UAIC/ISMA/dto/RegistrationRequest.java
  src/main/java/com/UAIC/ISMA/dto/ResetPasswordRequest.java
  src/main/java/com/UAIC/ISMA/exception/DuplicateEmailException.java
  src/main/java/com/UAIC/ISMA/repository/RoleRepository.java
  src/main/java/com/UAIC/ISMA/repository/UserRepository.java
  src/main/java/com/UAIC/ISMA/service/EmailService.java
  src/test/java/com/UAIC/ISMA/controller/RegisterControllerTest.java
Labels: ready-to-run

#58 db seed
  src/main/java/com/UAIC/ISMA/dbseed/DatabaseSeeder.java
Labels: ready-to-run

#55 BE-Refactor-303-Refactor-Laboratory
  src/main/java/com/UAIC/ISMA/controller/EquipmentController.java
  src/main/java/com/UAIC/ISMA/controller/LaboratoryController.java
  src/main/java/com/UAIC/ISMA/dto/EquipmentDTO.java
  src/main/java/com/UAIC/ISMA/dto/LaboratoryDTO.java
  src/main/java/com/UAIC/ISMA/entity/Equipment.java
  src/main/java/com/UAIC/ISMA/entity/Laboratory.java
  src/main/java/com/UAIC/ISMA/repository/LaboratoryRepository.java
  src/main/java/com/UAIC/ISMA/service/EquipmentService.java
  src/main/java/com/UAIC/ISMA/service/LaboratoryService.java
  src/test/java/com/UAIC/ISMA/controller/EquipmentControllerTest.java
  src/test/java/com/UAIC/ISMA/controller/LaboratoryControllerTest.java
  src/test/java/com/UAIC/ISMA/service/LaboratoryServiceTest.java
Labels: ready-to-run

#60 fixes
  src/main/java/com/UAIC/ISMA/entity/Equipment.java
Labels: ready-to-run

#61 Be refactor 303 refactor laboratory
  src/main/java/com/UAIC/ISMA/entity/Laboratory.java
Labels: ready-to-run

#62 Refactorizare AuditLog+AccessRequestFilter-REFACUT
  pom.xml
  src/main/java/com/UAIC/ISMA/controller/AuditLogController.java
  src/main/java/com/UAIC/ISMA/dto/AccessRequestFilterDTO.java
  src/main/java/com/UAIC/ISMA/dto/AuditLogDTO.java
  src/main/java/com/UAIC/ISMA/repository/AuditLogRepository.java
  src/main/java/com/UAIC/ISMA/service/AuditLogService.java
  src/test/java/com/UAIC/ISMA/controller/AuditLogControllerTest.java
Labels: ready-to-run

#65 Equipment-SearchEndpoit-Fixes
  src/main/java/com/UAIC/ISMA/controller/EquipmentController.java
Labels: ready-to-run

#67 Refactorizare entitatea AccessRequest REFACUT
  src/main/java/com/UAIC/ISMA/dbseed/DatabaseSeeder.java
Labels: ready-to-run

#66 Be 303 refactorizare login+auth+virtualaccess
  src/main/java/com/UAIC/ISMA/config/JwtUtil.java
  src/main/java/com/UAIC/ISMA/config/SecurityConfig.java
  src/main/java/com/UAIC/ISMA/config/UserDetailsImpl.java
  src/main/java/com/UAIC/ISMA/controller/AccessRequestController.java
  src/main/java/com/UAIC/ISMA/controller/AuthController.java
  src/main/java/com/UAIC/ISMA/controller/RegisterController.java
  src/main/java/com/UAIC/ISMA/controller/UserController.java
  src/main/java/com/UAIC/ISMA/controller/VirtualAccessController.java
  src/main/java/com/UAIC/ISMA/dto/VirtualAccessDTO.java
  src/main/java/com/UAIC/ISMA/entity/VirtualAccess.java
  src/main/java/com/UAIC/ISMA/exception/VirtualAccessAlreadyExistsException.java
  src/main/java/com/UAIC/ISMA/mapper/VirtualAccessMapper.java
  src/main/java/com/UAIC/ISMA/repository/UserRepository.java
  src/main/java/com/UAIC/ISMA/service/AccessRequestService.java
  src/main/java/com/UAIC/ISMA/service/EmailService.java
  src/main/java/com/UAIC/ISMA/service/UserDetailsImplService.java
  src/main/java/com/UAIC/ISMA/service/VirtualAccessService.java
  src/test/java/com/UAIC/ISMA/service/AccessRequestServiceFilterTest.java
  src/test/java/com/UAIC/ISMA/service/AccessRequestServiceTest.java
  src/test/java/com/UAIC/ISMA/service/VirtualAccessServiceTest.java
Labels: ready-to-run

#64 Refactor lab documents
  pom.xml
  src/main/java/com/UAIC/ISMA/IsmaApplication.java
  src/main/java/com/UAIC/ISMA/controller/LabDocumentController.java
  src/main/java/com/UAIC/ISMA/dbseed/DatabaseSeeder.java
  src/main/java/com/UAIC/ISMA/dto/LabDocumentDTO.java
  src/main/java/com/UAIC/ISMA/entity/LabDocument.java
  src/main/java/com/UAIC/ISMA/entity/Laboratory.java
  src/main/java/com/UAIC/ISMA/mapper/LabDocumentsMapper.java
  src/main/java/com/UAIC/ISMA/repository/LabDocumentRepository.java
  src/main/java/com/UAIC/ISMA/service/LabDocumentService.java
  src/main/resources/application.properties
  src/test/java/com/UAIC/ISMA/controller/LabDocumentControllerTest.java
  src/test/java/com/UAIC/ISMA/service/LabDocumentServiceTest.java
Labels: ready-to-run

#72 endpoint pt a obtine rolurile userului conectat
  src/main/java/com/UAIC/ISMA/config/SecurityConfig.java
  src/main/java/com/UAIC/ISMA/controller/AuthController.java
Labels: ready-to-run

#74 changed user when AccessRequest is created
  src/main/java/com/UAIC/ISMA/service/AccessRequestService.java
Labels: ready-to-run

#76 gestionarea permisiunilor in functie de rol
  src/main/java/com/UAIC/ISMA/controller/AccessRequestController.java
  src/main/java/com/UAIC/ISMA/controller/AuditLogController.java
  src/main/java/com/UAIC/ISMA/controller/EquipmentController.java
  src/main/java/com/UAIC/ISMA/controller/LabDocumentController.java
  src/main/java/com/UAIC/ISMA/controller/LaboratoryController.java
  src/main/java/com/UAIC/ISMA/controller/NotificationController.java
  src/main/java/com/UAIC/ISMA/controller/RequestApprovalController.java
  src/main/java/com/UAIC/ISMA/controller/RequestDocumentController.java
  src/main/java/com/UAIC/ISMA/controller/RoleController.java
Labels: ready-to-run

#77 modificari pt myAccessRequest
  src/main/java/com/UAIC/ISMA/controller/MyAccessRequestController.java
  src/main/java/com/UAIC/ISMA/repository/AccessRequestRepository.java
  src/test/java/com/UAIC/ISMA/controller/MyAccessRequestControllerTest.java
Labels: ready-to-run

#79 modificari repo
  src/main/java/com/UAIC/ISMA/repository/AccessRequestRepository.java
Labels: ready-to-run

#82 size fix
  src/main/java/com/UAIC/ISMA/dto/EquipmentDTO.java
Labels: ready-to-run

#83 Update Equipment.java
  src/main/java/com/UAIC/ISMA/entity/Equipment.java
Labels: ready-to-run

#84 modificari access request my access request
  src/main/java/com/UAIC/ISMA/controller/AccessRequestController.java
  src/main/java/com/UAIC/ISMA/controller/MyAccessRequestController.java
  src/main/java/com/UAIC/ISMA/repository/AccessRequestRepository.java
  src/main/java/com/UAIC/ISMA/service/AccessRequestService.java
  src/test/java/com/UAIC/ISMA/controller/AccessRequestControllerTest.java
  src/test/java/com/UAIC/ISMA/controller/MyAccessRequestControllerTest.java
  src/test/java/com/UAIC/ISMA/service/AccessRequestServiceTest.java
Labels: ready-to-run

#85 modificari filtrare
  src/main/java/com/UAIC/ISMA/controller/AccessRequestController.java
  src/main/java/com/UAIC/ISMA/repository/AccessRequestRepository.java
  src/main/java/com/UAIC/ISMA/service/AccessRequestService.java
  src/test/java/com/UAIC/ISMA/controller/AccessRequestControllerFilterTest.java
Labels: ready-to-run

#86 Update AccessRequestController.java
  src/main/java/com/UAIC/ISMA/controller/AccessRequestController.java
Labels: ready-to-run

#90 adjusted my exceptions and status codes
  src/main/java/com/UAIC/ISMA/controller/RequestApprovalController.java
  src/main/java/com/UAIC/ISMA/service/RequestApprovalService.java
Labels: ready-to-run

#92 adaug exceptii clare si mesaje de eroare pentru virtual-access, login…
  src/main/java/com/UAIC/ISMA/controller/AuthController.java
  src/main/java/com/UAIC/ISMA/controller/RegisterController.java
  src/main/java/com/UAIC/ISMA/dto/AuthRequest.java
  src/main/java/com/UAIC/ISMA/dto/RegistrationRequest.java
  src/main/java/com/UAIC/ISMA/dto/ResetPasswordRequest.java
  src/main/java/com/UAIC/ISMA/dto/RolesResponse.java
  src/main/java/com/UAIC/ISMA/exception/GlobalExceptionHandler.java
  src/main/java/com/UAIC/ISMA/exception/MissingAccessRequestIdException.java
  src/main/java/com/UAIC/ISMA/exception/VirtualAccessAlreadyExistsException.java
  src/main/java/com/UAIC/ISMA/service/VirtualAccessService.java
Labels: ready-to-run

#93 Adaugare exceptii si mesaje de eroare AuditLog
  src/main/java/com/UAIC/ISMA/controller/AuditLogController.java
  src/main/java/com/UAIC/ISMA/dto/AuditLogDTO.java
  src/main/java/com/UAIC/ISMA/service/AuditLogService.java
Labels: ready-to-run

#87 Refactorizare-Exception-Handler-Equipment
  src/main/java/com/UAIC/ISMA/controller/EquipmentController.java
  src/main/java/com/UAIC/ISMA/exception/GlobalExceptionHandler.java
Labels: ready-to-run

#95 modificari db-seed
  src/main/java/com/UAIC/ISMA/dbseed/DatabaseSeeder.java
Labels: ready-to-run

#104 deleted bad exception
  src/main/java/com/UAIC/ISMA/controller/AuthController.java
Labels: ready-to-run

#106 added a new endpoint for deleting users, request from Daniel
  src/main/java/com/UAIC/ISMA/controller/UserController.java
  src/main/java/com/UAIC/ISMA/service/EmailService.java
Labels: ready-to-run

#107 fixed a 500 error
  src/main/java/com/UAIC/ISMA/service/UserDetailsImplService.java
Labels: ready-to-run
